"use client";
import { useEffect,useState } from "react";
import QRCode from "qrcode";
import { ChevronLeft,ChevronRight,Download,Printer,TicketCheck,TriangleAlert } from "lucide-react";
import type { AccountTicketBundle } from "@/lib/account/data";

function save(url:string,name:string){const a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();}
function when(v:string,tz:string){return new Intl.DateTimeFormat("en-LK",{weekday:"long",year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:true,timeZone:tz}).format(new Date(v));}

export default function AccountTicketViewer({bundle}:{bundle:AccountTicketBundle}){
 const [active,setActive]=useState(0); const [codes,setCodes]=useState<Record<string,string>>({});
 useEffect(()=>{let off=false;Promise.all(bundle.tickets.map(async t=>[t.id,await QRCode.toDataURL(t.qrToken,{width:460,margin:4,errorCorrectionLevel:"M",color:{dark:"#0E1721",light:"#FFFFFF"}})] as const)).then(x=>{if(!off)setCodes(Object.fromEntries(x));});return()=>{off=true};},[bundle.tickets]);
 const t=bundle.tickets[active]; if(!t)return <div className="border border-amber-200 bg-amber-50 p-6 text-sm text-amber-800"><TriangleAlert className="mb-3 h-5 w-5"/>Tickets have not been issued for this order yet.</div>;
 const qr=codes[t.id]; const due=bundle.paymentMethod==="ON_ARRIVAL"&&bundle.paymentStatus!=="PAID";
 return <div><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] uppercase tracking-[.2em] text-[#7D8A95]">Order {bundle.orderNumber}</div><div className="mt-1 text-sm text-[#31465A]">Ticket {active+1} of {bundle.tickets.length}</div></div><div className="flex gap-2"><button disabled={!qr} onClick={()=>qr&&save(qr,`${t.ticketNumber}-QR.png`)} className="inline-flex h-10 items-center gap-2 border border-[#C2CBD2] bg-white px-4 text-xs hover:border-[#2271B1] disabled:opacity-40"><Download className="h-4 w-4"/>Save QR</button><button onClick={()=>window.print()} className="inline-flex h-10 items-center gap-2 border border-[#C2CBD2] bg-white px-4 text-xs hover:border-[#2271B1]"><Printer className="h-4 w-4"/>Print</button></div></div>
 <div className="relative overflow-hidden border border-[#C2CBD2]/70 bg-white shadow-[0_20px_70px_rgba(14,23,33,.08)]"><img src="/butterfly/RTop.webp" alt="" aria-hidden="true" className="pointer-events-none absolute -right-16 -top-14 w-[380px] opacity-[.07]"/><div className="grid lg:grid-cols-[1fr_300px]"><section className="relative p-7 sm:p-10"><div className="absolute bottom-0 left-0 top-0 w-2 bg-[#2271B1]"/><div className="pl-3"><div className="text-[10px] font-mono uppercase tracking-[.3em] text-[#2271B1]">Official admission pass • 2026</div><h1 className="mt-3 font-gemola text-4xl sm:text-5xl">SWARA RANJANA</h1><div className="mt-7 text-xl text-[#31465A]">{t.ticketTypeName}</div><div className="mt-1 text-xs uppercase tracking-[.16em] text-[#7D8A95]">{t.seatingZone??"Admission"}</div><div className="mt-9 grid gap-6 sm:grid-cols-2"><div><div className="text-[10px] uppercase text-[#7D8A95]">Guest</div><div className="mt-1 text-sm font-medium">{t.attendeeName||bundle.customerName}</div></div><div><div className="text-[10px] uppercase text-[#7D8A95]">Date & time</div><div className="mt-1 text-sm font-medium">{when(bundle.startsAt,bundle.timezone)}</div></div><div><div className="text-[10px] uppercase text-[#7D8A95]">Venue</div><div className="mt-1 text-sm font-medium">{bundle.venueName}</div></div><div><div className="text-[10px] uppercase text-[#7D8A95]">Ticket</div><div className="mt-1 font-mono text-sm font-semibold text-[#2271B1]">{t.ticketNumber}</div></div></div><div className={`mt-8 inline-flex items-center gap-2 border px-3 py-2 text-xs font-medium ${t.status==="VALID"?"border-emerald-200 bg-emerald-50 text-emerald-700":t.status==="USED"?"border-amber-200 bg-amber-50 text-amber-700":"border-red-200 bg-red-50 text-red-700"}`}><TicketCheck className="h-4 w-4"/>{t.status}</div></div></section><aside className="flex flex-col items-center justify-center border-t border-dashed border-[#C2CBD2] p-7 text-center lg:border-l lg:border-t-0"><div className="text-[10px] uppercase tracking-[.22em] text-[#7D8A95]">Scan at entrance</div><div className="mt-5 flex h-[225px] w-[225px] items-center justify-center bg-white">{qr?<img src={qr} alt={`QR code for ${t.ticketNumber}`} className="h-full w-full"/>:<span className="text-xs text-[#7D8A95]">Generating QR…</span>}</div><div className="mt-4 font-mono text-sm font-semibold">{t.ticketNumber}</div><div className={`mt-5 w-full border px-3 py-3 text-xs font-semibold ${due?"border-amber-200 bg-amber-50 text-amber-800":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{due?"PAYMENT DUE AT ENTRY":"PAYMENT CONFIRMED"}</div></aside></div></div>
 {bundle.tickets.length>1&&<div className="mt-5 flex items-center justify-between"><button onClick={()=>setActive(i=>i===0?bundle.tickets.length-1:i-1)} className="inline-flex items-center gap-1 text-xs uppercase"><ChevronLeft className="h-4 w-4"/>Previous</button><span className="text-xs text-[#7D8A95]">{active+1}/{bundle.tickets.length}</span><button onClick={()=>setActive(i=>i===bundle.tickets.length-1?0:i+1)} className="inline-flex items-center gap-1 text-xs uppercase">Next<ChevronRight className="h-4 w-4"/></button></div>}
 </div>;
}
