create schema if not exists private;

revoke all on schema private from public, anon, authenticated;

create table if not exists private.server_rate_limit_events (
  id bigint generated by default as identity primary key,
  scope text not null check (char_length(scope) between 1 and 80),
  key_hash text not null check (char_length(key_hash) between 16 and 128),
  created_at timestamptz not null default clock_timestamp()
);

create index if not exists server_rate_limit_events_lookup_idx
  on private.server_rate_limit_events (scope, key_hash, created_at desc);

revoke all on table private.server_rate_limit_events from public, anon, authenticated;
revoke all on sequence private.server_rate_limit_events_id_seq from public, anon, authenticated;

create or replace function public.consume_server_rate_limit(
  p_scope text,
  p_key_hash text,
  p_limit integer,
  p_window_seconds integer
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_now timestamptz := clock_timestamp();
  v_count integer := 0;
  v_oldest timestamptz;
  v_retry_after integer := 0;
begin
  if p_scope is null or char_length(btrim(p_scope)) < 1 or char_length(p_scope) > 80
     or p_key_hash is null or char_length(p_key_hash) < 16 or char_length(p_key_hash) > 128
     or p_limit < 1 or p_limit > 1000
     or p_window_seconds < 1 or p_window_seconds > 86400 then
    return jsonb_build_object('ok', false, 'code', 'INVALID_RATE_LIMIT');
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_scope || ':' || p_key_hash, 0));

  delete from private.server_rate_limit_events
   where scope = p_scope
     and key_hash = p_key_hash
     and created_at < v_now - interval '24 hours';

  select count(*)::integer, min(created_at)
    into v_count, v_oldest
    from private.server_rate_limit_events
   where scope = p_scope
     and key_hash = p_key_hash
     and created_at > v_now - (p_window_seconds * interval '1 second');

  if v_count >= p_limit then
    v_retry_after := greatest(
      1,
      ceil(extract(epoch from ((v_oldest + (p_window_seconds * interval '1 second')) - v_now)))::integer
    );

    return jsonb_build_object(
      'ok', true,
      'allowed', false,
      'remaining', 0,
      'retry_after_seconds', v_retry_after
    );
  end if;

  insert into private.server_rate_limit_events(scope, key_hash, created_at)
  values (p_scope, p_key_hash, v_now);

  return jsonb_build_object(
    'ok', true,
    'allowed', true,
    'remaining', greatest(0, p_limit - v_count - 1),
    'retry_after_seconds', 0
  );
end;
$function$;

revoke all on function public.consume_server_rate_limit(text, text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_server_rate_limit(text, text, integer, integer) to service_role;
