import type { Metadata } from "next";
import Link from "next/link";
import { CalendarDays, CreditCard, LogOut, MapPin, Ticket } from "lucide-react";
import { signOutCustomer } from "@/app/account/actions";
import { getCustomerAccountData } from "@/lib/account/data";
import { requireCustomer } from "@/lib/auth/requireCustomer";

export const dynamic="force-dynamic"; export const revalidate=0;
export const metadata:Metadata={title:"My Tickets — Swara Ranjana",robots:{index:false,follow:false,nocache:true}};
const date=(v:string,tz="Asia/Colombo")=>v?new Intl.DateTimeFormat("en-LK",{dateStyle:"medium",timeStyle:"short",timeZone:tz}).format(new Date(v)):"Date TBA";
const payment=(m:string|null)=>m==="ON_ARRIVAL"?"Pay on arrival":m==="BANK_SLIP"?"Bank transfer":m==="CARD"?"Card / OnePay":"Payment not selected";

export default async function AccountPage(){
  const {supabase,customer}=await requireCustomer(); const account=await getCustomerAccountData(supabase,customer);
  return <main className="min-h-screen bg-[#F7F9FA] px-4 py-10 text-[#0E1721] sm:py-14"><div className="mx-auto max-w-6xl">
    <header className="flex flex-col justify-between gap-5 border-b border-[#C2CBD2] pb-6 sm:flex-row sm:items-end"><div><Link href="/" className="text-[10px] uppercase tracking-[.2em] text-[#7D8A95] hover:text-[#2271B1]">← Swara Ranjana</Link><div className="mt-5 text-[10px] font-mono uppercase tracking-[.3em] text-[#2271B1]">Customer profile</div><h1 className="mt-2 font-gemola text-4xl sm:text-5xl">My tickets.</h1><p className="mt-2 text-sm text-[#7D8A95]">{customer.full_name} • {customer.email}</p></div><form action={signOutCustomer}><button className="inline-flex h-10 items-center gap-2 border border-[#C2CBD2] bg-white px-4 text-xs text-[#31465A] hover:border-[#2271B1] hover:text-[#2271B1]"><LogOut className="h-4 w-4"/>Sign out</button></form></header>
    <div className="mt-8 grid gap-6 lg:grid-cols-[270px_1fr]"><aside className="h-fit border border-[#C2CBD2]/70 bg-white p-5"><div className="text-[10px] uppercase tracking-[.18em] text-[#7D8A95]">Account</div><div className="mt-4 space-y-4 text-sm"><div><div className="text-[10px] uppercase text-[#7D8A95]">Name</div><div className="mt-1 font-medium">{customer.full_name}</div></div><div><div className="text-[10px] uppercase text-[#7D8A95]">Email</div><div className="mt-1 break-all text-[#31465A]">{customer.email}</div></div><div><div className="text-[10px] uppercase text-[#7D8A95]">Phone</div><div className="mt-1 text-[#31465A]">{customer.phone||"—"}</div></div></div><div className="mt-6 border-t border-[#C2CBD2]/60 pt-5 text-xs leading-relaxed text-[#7D8A95]">Future reservations using this same email appear here automatically.</div></aside>
    <section><div className="flex items-end justify-between"><div><div className="text-[10px] uppercase tracking-[.18em] text-[#7D8A95]">Reservations & admissions</div><h2 className="mt-1 font-gemola text-3xl">Orders</h2></div><Link href="/tickets" className="text-xs text-[#2271B1] hover:underline">Reserve more →</Link></div>
    {!account.orders.length?<div className="mt-5 border border-[#C2CBD2] bg-white p-10 text-center"><Ticket className="mx-auto h-6 w-6 text-[#7D8A95]"/><p className="mt-3 text-sm font-medium">No reservations found.</p></div>:<div className="mt-5 space-y-4">{account.orders.map(o=>{const expired=o.status==="PENDING"&&!!o.expiresAt&&new Date(o.expiresAt).getTime()<=Date.now(); return <article key={o.id} className="border border-[#C2CBD2]/70 bg-white p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="font-mono text-xs font-semibold text-[#2271B1]">{o.orderNumber}</div><h3 className="mt-2 font-gemola text-2xl">{o.eventName}</h3><div className="mt-3 flex flex-wrap gap-4 text-xs text-[#7D8A95]"><span className="inline-flex items-center gap-1.5"><CalendarDays className="h-3.5 w-3.5"/>{date(o.eventStartsAt,o.eventTimezone)}</span><span className="inline-flex items-center gap-1.5"><MapPin className="h-3.5 w-3.5"/>{o.venueName}</span></div></div><div className="flex gap-2"><span className="border border-[#C2CBD2] px-2.5 py-1 text-[10px] font-semibold">{expired?"EXPIRED":o.status}</span><span className={`border px-2.5 py-1 text-[10px] font-semibold ${o.paymentStatus==="PAID"?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-amber-200 bg-amber-50 text-amber-700"}`}>{o.paymentStatus.replaceAll("_"," ")}</span></div></div>
    <div className="mt-5 grid gap-3 border-y border-[#C2CBD2]/50 py-4 sm:grid-cols-3"><div><div className="text-[9px] uppercase text-[#7D8A95]">Tickets</div><div className="mt-1 text-sm font-medium">{o.items.reduce((s,i)=>s+i.quantity,0)}</div></div><div><div className="text-[9px] uppercase text-[#7D8A95]">Payment</div><div className="mt-1 text-sm font-medium">{payment(o.paymentMethod)}</div></div><div><div className="text-[9px] uppercase text-[#7D8A95]">Total</div><div className="mt-1 text-sm font-medium">{o.currency} {o.total.toLocaleString("en-LK")}</div></div></div>
    <div className="mt-4 space-y-2">{o.items.map(i=><div key={i.id} className="flex justify-between text-xs"><span>{i.ticketTypeName} × {i.quantity}</span><span className="text-[#7D8A95]">{o.currency} {i.totalPrice.toLocaleString("en-LK")}</span></div>)}</div>{o.slipStatus==="PENDING"&&<div className="mt-4 border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">Your payment slip is awaiting verification.</div>}<div className="mt-5 flex flex-wrap gap-2">{o.tickets.length>0&&<Link href={`/account/orders/${o.id}`} className="inline-flex h-10 items-center gap-2 bg-[#0E1721] px-4 text-xs text-white hover:bg-[#2271B1]"><Ticket className="h-4 w-4"/>View {o.tickets.length===1?"ticket":"tickets"}</Link>}{o.status==="PENDING"&&!expired&&<Link href={`/payment/${o.orderNumber}?token=${encodeURIComponent(o.accessToken)}`} className="inline-flex h-10 items-center gap-2 border border-[#C2CBD2] px-4 text-xs text-[#31465A] hover:border-[#2271B1] hover:text-[#2271B1]"><CreditCard className="h-4 w-4"/>Continue payment</Link>}</div></article>})}</div>}
    </section></div>
  </div></main>;
}
